- name: variables from files level
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
    - name: check variable in vars_files
      ansible.builtin.debug:
        msg: "Hi I am learning {{Course}}, trainer is {{Trainer}}, duration is {{Duration}}"
  