- name: variables from PLAY level
  hosts: localhost
  tasks:
    - name: variables test
      ansible.builtin.debug:
        msg: "Hi I am learning {{Course}}, trainer is {{Trainer}}, duration is {{Duration}}"