- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: print persons
    ansible.builtin.package:
      msg: "{{item}}" # item is a default keyword
      state: present

    loop: 
    - mysql
    - postfix