- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: install multiple packages
    ansible.builtin.package:
      name: "{{item.name}}" 
      state: "{{item.state}}"

    loop: 
    - {name: 'git', state: 'present'} # item with key value
    - {name: 'mysql', state: 'absent'}
    - {name: 'postfix', state: 'obsent'}